import path from "node:path";
import type { Client } from "pg";

/** Committed migrations generated by Drizzle Kit (see drizzle.config.ts). */
export const migrationsFolder = path.resolve(
  import.meta.dirname,
  "../../../drizzle",
);

/** Must match `migrations` in drizzle.config.ts. */
export const migrationJournal = {
  migrationsSchema: "drizzle",
  migrationsTable: "__drizzle_migrations",
} as const;

export async function appliedMigrationCount(client: Client): Promise<number> {
  return countRowsIfTableExists(client, "drizzle.__drizzle_migrations");
}

/**
 * Counts rows in a fixed, reviewed table, or 0 if it does not exist yet.
 * Two queries are needed: PostgreSQL resolves table names at parse time.
 */
export async function countRowsIfTableExists(
  client: Client,
  table: "drizzle.__drizzle_migrations" | "app.system_metadata",
): Promise<number> {
  const { rows } = await client.query<{ exists: boolean }>(
    "SELECT to_regclass($1) IS NOT NULL AS exists",
    [table],
  );
  if (!rows[0].exists) return 0;
  const count = await client.query<{ n: number }>(
    `SELECT count(*)::int AS n FROM ${table}`,
  );
  return count.rows[0].n;
}
